### PR TITLE
Add some failing tests showing that stdin/out/err are bounded

### PR DESCRIPTION
**Pull request by weissi**
# Problems
#### Problem 1

Chores at the moment suffers from the problem that whenever stdin/out/err are larger than a `pipe(2)` (`BIG_PIPE_SIZE` = `64*1024` on Yosemite. And if I remember correctly `PIPE_SIZE` = `16 * 1024` on Mavericks and below) the program will hang forever. For now, I added two test cases `testCanHaveInputLongerThanPipeSize` and `testCanHaveOutputLongerThanPipeSize` which demonstrate that. Please note the tests won't actually fail, they'll just sit there forever and wait for the other end of the pipe to be service (which will never happen).
#### Problem 2

Chores is based on `NSTask` and therefore all `execve(2)` errors are communicated through exceptions, that's obviously a problem in Swift. Chores tries to prevalidate that by checking that the path exists. That's however racy and doesn't cover cases like `EISDIR` (file to execute is directory), `EACCESS` (no exec bit set), and others. I added two test cases `testExecuteDirectory` and `testExecuteNonExecutableFile` which are supposed to demo the problem but they succeed which is problem 3.
#### Problem 3

It seems like a test that throws an exception just silently succeeds?!
# Comment

Probably this PR shouldn't be merged directly as it demonstrates (but doesn't fix) the problems.

### CODE REVIEW

**Comment by neonichu** [comment]
Cool, thanks for those tests :)

Problem 3 is a known issue in xctester: https://github.com/neonichu/xctester/issues/3

**Comment by weissi** [comment]
Cool! If you actually want to merge some of that stuff, I'm more than happy to split it to multiple commits/PRs.

At Bromium we actually have a drop-in replacement for `NSTask` which doesn't throw exceptions, maybe we can open-source that. The API is the same, just `- (void)launch` is `- (BOOL)launchWithError:(NSError **)`.

**Comment by neonichu** [comment]
Would be awesome if you could open-source Bromium's `NSTask` replacement - I think we talked about that back at Cmd+R last year :)

What can be done about the first problem?

FWIW, xctester 0.1.5 does correctly handle exceptions now, so if you break out the tests for the second problem, I can merge them.

**Comment by weissi** [comment]
Yes, sorry, talked with a couple of people about that, finally sent an email with asking about open-sourcing it. 🙏things like that can be done without lawyers.

The hanging problem is only to solve having some entity service the pipes whilst the child process is running. `dispatch_io` can be used to do that fairly easily, I'd be happy to contribute that. But really it's two different problems and slightly more nuanced:
1. `stdin` pipe: That one is fairly easy as you get the data and just write when appropriate. ✔︎
2. `stdout`/`stderr` pipes: They're just as easy to implement with the caveat that they might consume unbounded amounts of memory to construct the `NSData` for the returned data as you can't predict how much it'll be. Imagine someone launching `/usr/bin/yes` for example (you might argue that the user then deserves it 😜)... One possibility would be to continuously call back with `dispatch_data_t` or `NSData` chunks while they can be read from the queue. So basically you'd spawn a process and whenever there's something to read from stdout/err your closure gets invoked with the latest chunk of data. That'd solve the unbounded amounts of memory issue but makes the API harder to use. Does that make sense?

**Comment by neonichu** [comment]
Yep, makes sense. 

I'm thinking the API could be giving you callbacks by default. We also wrap it into the simple API we currently have and that would just terminate the process once the memory consumption goes beyond a fixed threshold (e.g. `PIPE_SIZE`). That would keep basic usage as easy as it is now, while avoiding hanging processes and would also enable more complex usage scenarios. Is that reasonable?

Speaking of `/usr/bin/yes` - maybe it would also make sense to have a timeout after which the process is terminated for cases where the task never exits?

**Comment by weissi** [comment]
@neonichu finally, it's open-sourced: https://github.com/BromiumInc/BromiumCoreUtils/blob/master/BromiumCoreUtils/BRUTask.m

**Comment by neonichu** [comment]
`.m` 😱 — but seriously, awesome :+1: 

Would like to build on top of `BRUTask` to make this more robust, would you accept a PR to BromiumCoreUtils which adds a podspec and potentially a `Package.swift` (not 100% it's possible)?

**Comment by weissi** [comment]
I know `.m` 😉. I'm pretty sure a colleague is working on a podspec already actually. PRs should get accepted.

**Pull request closed without merging**
